ARG ARCH=amd64
ARG BASE_IMG=gcr.io/distroless/static-debian12@sha256:aad6bf1f8a12245247887a9026f8e847b60a37cf59747cca1c157ec74964a4c5
FROM --platform=linux/${ARCH} ${BASE_IMG}

ADD etcd /usr/local/bin/
ADD etcdctl /usr/local/bin/
ADD etcdutl /usr/local/bin/

WORKDIR /var/etcd/
WORKDIR /var/lib/etcd/

EXPOSE 2379 2380

# Define default command.
CMD ["/usr/local/bin/etcd"]
