---
name: Robustness
on: [push, pull_request]
permissions: read-all
jobs:
  main-arm64:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 1000
      testTimeout: 200m
      artifactName: main-arm64
      runs-on: "['macos-14']"
      scenario: TestRobustnessExploratory/Kubernetes/LowTraffic/ClusterOfSize1
      lazyfsEnabled: false
